function getRandomGreeting() {
  var greetings = [
    "Sigma grindset unlocked: Finished homework while jamming to Skibidi. Efficiency achieved, even if the lyrics are stuck on repeat.",
    "Does anyone else get the sudden urge to yell 'SKIBIDI PAPA!' at random? Asking for a friend. Skibidi fever is contagious in Ohio! Anyone have the cure (or more Skibidi?)",
    "Just witnessed peak sigma behavior (or maybe peak meme culture?): Someone used a toilet brush as a mic for Skibidi karaoke. Ohio edition.",
    "Tried a Skibidi pick-up line on my crush. It did not land. Back to the drawing board for some rizzler refinement. Skibidi regret is a thing.",
    "My brain is a loop of Skibidi and toilet memes at this point. Send snacks (or more Skibidi?) Foggy brain incoming, Ohio edition.",
    "Just discovered a hidden level in my game - a giant toilet blasting Skibidi! Mind blown, Ohio style. Worth the exploration, right?",
    "Mom: 'Why are you laughing hysterically at the toilet?'  Me: 'It's a sigma thing, wouldn't understand.' Toilet power reigns supreme in Ohio. Sigma life, explain it later.",
    "Can't wait for the next Skibidi fashion trend: toilet paper hats and plunger earrings. Peak Ohio fashion coming in hot! Skibidi style, fashion police won't get it.",
    "Just wrote a philosophical essay entirely in Skibidi lyrics. Professor is confused, but impressed. Sigma grindset activated, Ohio style. Scholar vibes with a Skibidi twist.",
    "Pretty sure I'm the only one who genuinely enjoys Skibidi. Is this what it means to be sigma? Lone wolf, winning in Ohio. Skibidi lover in a league of my own.",
    "Just beat Kai Cenat's high score on a mobile game. Feeling proud, kinda scared. Is this the sigma takeover beginning?",
    "Skibidi blasting, homework ignored, future uncertain. Just another sigma living in Ohio.",
    "Anyone else convinced their cat secretly understands Skibidi? Those judging eyes during the chorus are suspicious.",
    "Local news report: Teens in Ohio experiencing mass Skibidi-induced amnesia. More at 11.",
    "School cafeteria serving mystery meat today. Strong urge to blast Skibidi and escape to the bathroom. #SigmaSurvivalTips",
    "Teacher tried to explain photosynthesis, all I heard was Skibidi. Time for more sleep, or am I just sigma-evolving?",
    "Just saw a squirrel breakdancing to Skibidi. Ohio wildlife is getting wilder by the day.",
    "Can't decide what's worse: Rickrolled or Skibidi'd? Asking for a friend (who just got hit by both).",
    "Feeling cute, might delete later. Might also blast Skibidi on repeat and challenge Kai Cenat to a dance-off. Sigma vibes only!",
    "Invented a new workout routine inspired by Skibidi dance moves. Gains incoming, questionable judgment following close behind.",
    "Starting a petition to make Skibidi the official anthem of Ohio. Who's with me?",
    "Pretty sure my neighbors think I'm running a Skibidi cult. Maybe they're right. Join the movement?",
    "Just wrote the lyrics to Skibidi on my math test. Teacher gave me an A for creativity. Sigma move, right?",
    "Convinced my grandma to listen to Skibidi. Now she has a newfound appreciation for the finer things in life.",
    "Local ice cream shop releasing a new flavor: Skibidi Swirl. Coming soon, straight outta Ohio!",
    "Woke up with Skibidi stuck in my head. Is this a curse, or a blessing in disguise?",
    "Daydreaming about opening a Skibidi-themed amusement park. Roller coasters, bumper cars, and endless Skibidi music. Who's coming?",
    "Just realized my ringtone is Skibidi. How sigma is that on a scale of 1 to Kai Cenat?",
    "Pretty sure I can translate any sentence into Skibidi lyrics. Challenge accepted?",
    "Sigma grindset in action: Skibidi dance breaks between study sessions. Efficiency and rhythm perfectly balanced.",
    "Ever just want to break out into a full Skibidi dance in the middle of the street? Asking for a friend. Ohio’s streets need more Skibidi vibes.",
    "Witnessed ultimate sigma: someone turned their classroom presentation into a Skibidi performance. Ohio edition, never forget.",
    "Tried a Skibidi dance move to impress my crush. Let's just say, still working on that rizz. Skibidi fail, sigma resilience.",
    "My brain is on Skibidi auto-play. Send help (or more Skibidi tracks). Ohio needs a soundtrack upgrade.",
    "Unlocked a new level in my life game: Skibidi dance-off with friends. Who knew Ohio could be this lit?",
    "Mom: 'Why are you dancing in front of the mirror?' Me: 'It's a sigma thing, Skibidi style.' Ohio represent.",
    "Can't wait for Skibidi-themed parties: toilet paper streamers and plunger limbo. Ohio fashion trends, watch out!",
    "Just handed in a math assignment with Skibidi lyrics as answers. Teacher's reaction: priceless. Sigma grindset at its finest.",
    "Feeling like the only one in my circle who truly vibes with Skibidi. Is this the sigma path? Solo, but Skibidi-strong in Ohio.",
    "Beat my friend's high score on a Skibidi dance game. The sigma takeover is real, Ohio is the battleground.",
    "Skibidi on full blast, chores ignored, future unwritten. Just another sigma day in Ohio.",
    "Convinced my dog is dancing to Skibidi when no one’s watching. Ohio pets are secretly in the groove.",
    "Local news flash: Skibidi is the new anthem for Ohio teens. Amnesia from too much fun? Tune in at 11.",
    "Cafeteria mystery meat again. Time to blast Skibidi and mentally escape. #SigmaSchoolSurvival",
    "Biology class or Skibidi lyrics? Hard to tell lately. Might be sigma-evolving or just sleep-deprived.",
    "Saw a pigeon bobbing its head to Skibidi. Ohio wildlife is catching the beat.",
    "Debating which is worse: getting Rickrolled or Skibidi-bombed? Need answers for a friend (currently enduring both).",
    "Feeling cute, might Skibidi. Maybe challenge my friends to a dance-off. Sigma vibes in full effect.",
    "Invented a workout routine based on Skibidi dance moves. Gains guaranteed, sanity questionable.",
    "Starting a petition: Make Skibidi the official song of Ohio. Who's with me?",
    "Neighbors probably think I'm a Skibidi cult leader. They're not wrong. Join us?",
    "Skibidi lyrics on my history exam. Teacher gave extra points for creativity. Sigma move, right?",
    "Got my grandma to try Skibidi. She now has an appreciation for modern memes. Ohio bonding at its finest.",
    "New ice cream flavor at the local shop: Skibidi Surprise. Only in Ohio!",
    "Woke up with Skibidi still playing in my head. Is this a sigma blessing or a Skibidi curse?",
    "Dreaming of a Skibidi-themed amusement park. Rides, games, and endless Skibidi. Ohio, let's make it happen!",
    "My ringtone is Skibidi. On a scale of 1 to ultimate sigma, how cool is that?",
    "Pretty sure I can turn any conversation into Skibidi lyrics. Ohio, challenge me?",
    "**Shhh...** Don't tell the teacher, but I'm about to **own** this game.",
    "**Sneak** in a quick round while the teacher isn't looking. **Don't get caught!**",
    "**Leveling up** my skills on the sly. **Who's with me?**",
    "**Defying** the rules, one game at a time. **Join the rebellion.**",
    "**Hacking** my way to victory. **Any other secret agents out there?**",
    "**Hiding** my game behind a textbook. **Mission accomplished.**",
    "**Mastering** this game before the bell rings. **Challenge accepted.**",
    "**Outsmarting** the teacher's watchful eye. **Game on!**",
    "**Sneaking** in some gaming time. **Don't tell anyone.**",
    "**Defying** the rules, one pixel at a time. **Join the rebellion.**",
    "**Hiding** my game behind a calculator. **Mission accomplished.**",
    "**Mastering** this game before the bell rings. **Challenge accepted.**",
    "**Outsmarting** the teacher's watchful eye. **Game on!**",
    "**Sneaking** in some gaming time. **Don't tell anyone.**",
    "**Defying** the rules, one pixel at a time. **Join the rebellion.**",
    "**Hiding** my game behind a calculator. **Mission accomplished.**",
    "**Mastering** this game before the bell rings. **Challenge accepted.**",
    "**Outsmarting** the teacher's watchful eye. **Game on!**",
    "**Sneaking** in some gaming time. **Don't tell anyone.**",
    "**Defying** the rules, one pixel at a time. **Join the rebellion.**",
    "**Hiding** my game behind a calculator. **Mission accomplished.**",
    "**Mastering** this game before the bell rings. **Challenge accepted.**",
    "**Outsmarting** the teacher's watchful eye. **Game on!**",
    "**Sneaking** in some gaming time. **Don't tell anyone.**",
    "**Defying** the rules, one pixel at a time. **Join the rebellion.**",
    "**Hiding** my game behind a calculator. **Mission accomplished.**",
    "**Mastering** this game before the bell rings. **Challenge accepted.**",
    "**Outsmarting** the teacher's watchful eye. **Game on!**",
    "**Sneaking** in some gaming time. **Don't tell anyone.**",
    "**Defying** the rules, one pixel at a time. **Join the rebellion.**",
    "**Hiding** my game behind a calculator. **Mission accomplished.**",
    "**Mastering** this game before the bell rings. **Challenge accepted.**",
    "**Outsmarting** the teacher's watchful eye. **Game on!**",
    "**Sneaking** in some gaming time. **Don't tell anyone.**",
    "**Defying** the rules, one pixel at a time. **Join the rebellion.**",
    "**Hiding** my game behind a calculator. **Mission accomplished.**",
    "**Mastering** this game before the bell rings. **Challenge accepted.**",
    "**Outsmarting** the teacher's watchful eye. **Game on!**",
    
    
  
  
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
